# Generated by Django 5.0.1 on 2024-01-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, default='', max_length=30)),
                ('test_number', models.IntegerField(default=0)),
                ('max_test_number', models.IntegerField(default=0)),
                ('first_boundary', models.IntegerField(default=0)),
                ('last_boundary', models.IntegerField(default=1)),
                ('show_number', models.BooleanField(default=False)),
                ('tests', models.TextField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
