# Generated by Django 5.0.1 on 2024-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_model',
            name='shuffle_variant',
            field=models.BooleanField(default=False),
        ),
    ]
