# Generated by Django 5.1.6 on 2025-03-02 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdfapp", "0003_auto_20240601_0933"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quiz_Model",
            new_name="QuizModel",
        ),
    ]
