# Generated by Django 5.1.6 on 2025-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_profile_model_profilemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilemodel",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="current_quiz_number",
            field=models.IntegerField(default=0, verbose_name="Current Quiz Number"),
        ),
    ]
